# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with the official Python image with a compatible version
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the necessary files for installing the package
COPY pyproject.toml /app/
COPY src /app/src

# Install build tools and dependencies
RUN pip install --no-cache-dir hatchling

# Install the package in the Docker container
RUN pip install .

# Expose any necessary ports (optional, depending on the server requirements)
# EXPOSE 8000

# Define the entry point for the container
CMD ["skydeckai-code-cli", "--tool", "get_system_info"]
